name: CI
on: push
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'
      - name: build linux
        run: |
          more ${{ secrets.FIREBASE_OPTIONS }} | base64 -d > lib/firebase_options.dart
          flutter format lib/firebase_options.dart
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter config --enable-linux-desktop
          flutter build linux
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'
      - name: build windows
        run: |
          more ${{ secrets.FIREBASE_OPTIONS }} | base64 -d > lib/firebase_options.dart
          flutter format lib/firebase_options.dart
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build windows
          flutter pub run msix:create
  other-builds:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [ 'android', 'web', 'macos', 'ios' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'
      - name: Build android/web/macos/ios
        run: |
          more ${{ secrets.FIREBASE_OPTIONS }} | base64 -d > lib/firebase_options.dart
          flutter format lib/firebase_options.dart
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
        if: matrix.platform == 'web'
        run: |
          flutter build web
        if: matrix.platform == 'android'
        run: |
          flutter build apk --debug
        if: matrix.platform == 'macos'
        run: |
          flutter config --enable-macos-desktop
          flutter build macos --debug
        if: matrix.platform == 'ios'
        run: |
          flutter build ios --debug --no-codesign